#ifndef SECRETS_H
#define SECRETS_H

// WiFi
#define WIFI_SSID       "SSID HERE"
#define WIFI_PASSWORD   "WIFI PASSWORD HERE"

// Blynk
#define BLYNK_TEMPLATE_ID   "CHANGE THIS TO YOUR TEMPLATE ID"
#define BLYNK_TEMPLATE_NAME "CHANGE THIS TO YOUR TEMPLATE NAME"
#define BLYNK_AUTH_TOKEN    "CHANGE THIS TO YOUR AUTH TOKEN"

// Google Script
#define SERVER_URL_STR "SERVER URL HERE"

#endif // SECRETS_H
